language: objective-c
osx_image: xcode7.3
before_install:
- gem install xcpretty -N
script:
- set -o pipefail
- xcodebuild -project CountryKit.xcodeproj -scheme CountryKit -sdk iphonesimulator  -destination "name=iPhone 6S Plus" ONLY_ACTIVE_ARCH=NO build | xcpretty -c
- pod lib lint --quick
